### PR TITLE
fix(retrieval): temporal_sort kwarg + half-life decay (#473)

### LINKED ISSUE #473: StructMemEval adapter calls retrieve_v2() with unsupported temporal_sort kwarg
Discovered while running the calibration pass for #437 with `/tmp/StructMemEval` populated. The adapter never reached this point in the prior canonical run because the data dir was missing — the "No cases found" silent-return path masked the real bug.

## Symptom

```
$ uv run python benchmarks/structmemeval_adapter.py --task location --bench big --retrieve-only /tmp/sme_smoke.json
Loading StructMemEval cases: task=location, bench=big
Loaded 42 cases

--- static_001: 3 sessions, 30 messages, 1 queries ---
Traceback (most recent call last):
  File ".../benchmarks/structmemeval_adapter.py", line 587, in <module>
    main()
  File ".../benchmarks/structmemeval_adapter.py", line 518, in main
    case_result: CaseResult = run_case(...)
  File ".../benchmarks/structmemeval_adapter.py", line 401, in run_case
    retrieved: str = query_aelfrice(store, query.question, budget=budget)
  File ".../benchmarks/structmemeval_adapter.py", line 264, in query_aelfrice
    result = retrieve(...)
TypeError: retrieve_v2() got an unexpected keyword argument 'temporal_sort'
```

## Diagnosis

`benchmarks/structmemeval_adapter.py:264-272` calls:
```python
result = retrieve(
    store=store,
    query=question,
    budget=budget,
    include_locked=False,
    use_hrr=True,
    use_bfs=True,
    temporal_sort=True,
)
```

The `retrieve` symbol resolves to `retrieve_v2` in `src/aelfrice/retrieval.py:1246`. That function's parameter list ends at `bm25f_cache` — there is no `temporal_sort` kwarg.

`git log -S "temporal_sort" -- benchmarks/structmemeval_adapter.py src/aelfrice/retrieval.py` shows the kwarg was introduced in #54 (P1 benchmark foundation) and never reconciled with `retrieve_v2`'s signature.

## Impact on #437

The canonical pass at `benchmarks/results/v2.0.0.json` shows all 4 StructMemEval invocations (location / accounting / recommendations / tree) failing with `"adapter exited 0 but did not write $TMPDIR/T/structmemeval_<task>.json"`. With data dirs populated, those failures will switch from silent-no-output (exit 0) to loud `TypeError` (exit 1). Either way the canonical numbers stay placeholder until this is fixed.

## Fix directions

1. **Add `temporal_sort` to `retrieve_v2`** — the wrapper's stated purpose is to mirror the lab v2.0.0 retrieval signature. If the lab supports temporal sorting, this is the right fix and the public surface gains a useful knob. Cost: a real design call on what `temporal_sort` means (recency-weighted re-rank? `created_at DESC`? interaction with BM25F / posterior_weight?).
2. **Drop `temporal_sort=True` from the adapter** — accept the public surface's default ordering, document the deviation. The adapter docstring at line 262 says temporal sort "helps the reader identify the current state vs historical states" for structured queries — losing it may cost score on location/accounting/recommendations/tree. Cost: bench-measurable score delta.

## Related dispatcher contract gap

The dispatcher currently conflates three different exit states under one error message:
- data dir missing (skipped, not a real failure)
- adapter crashed mid-run (real failure)
- adapter ran but produced no cases (silent — what happened on the prior canonical run)

The #437 gate commit (60e1b68) called for an `exit_code 2 = skipped_data_missing` contract. This incident is evidence the contract should be three-state: `0 = ok`, `2 = skipped_data_missing`, `1 = adapter_error`, with the dispatcher classifying accordingly. Worth a separate issue for the dispatcher work — flagging here for cross-link.

## Refs

- Adapter call: `benchmarks/structmemeval_adapter.py:264-272`
- Public surface: `src/aelfrice/retrieval.py:1246-1262`
- Calibration blocker: #437
- Origin commit: #54 (P1 benchmark foundation)

### PR DESCRIPTION
**Pull request by yoshi280**
Closes #473.

## What changed

`retrieve_v2()` now accepts:

- `temporal_sort: bool = False`
- `temporal_half_life_seconds: float | None = None`

When `temporal_sort=True`, the merged tier output is re-ranked by a multiplicative half-life decay `2 ** (-age_seconds / half_life)` against `created_at`, applied as a final factor on top of the upstream pipeline's rank order. Locked (L0) beliefs are pinned at the head and never re-ordered.

Half-life resolution mirrors `resolve_posterior_weight`:

1. `AELFRICE_TEMPORAL_HALF_LIFE_SECONDS` env var (positive float)
2. Explicit `temporal_half_life_seconds` kwarg
3. `[retrieval] temporal_half_life_seconds` in `.aelfrice.toml`
4. Default: `DEFAULT_TEMPORAL_HALF_LIFE_SECONDS` (7 days, per #473 A1=A)

Default `temporal_sort=False` means the retrieve_v2 ordering is byte-identical to v1.7.0 for callers that don't opt in — verified by `test_retrieve_v2_temporal_sort_off_is_byte_identical`.

## Why

`benchmarks/structmemeval_adapter.py:264-272` was already calling `retrieve_v2(..., temporal_sort=True)` since #54, but `retrieve_v2`'s signature ended at `bm25f_cache`. The mismatch was masked while `/tmp/StructMemEval` was empty (silent "no cases" return), and surfaced as `TypeError: retrieve_v2() got an unexpected keyword argument 'temporal_sort'` once the data dir was populated. This blocked 4/11 canonical invocations in the #437 calibration pass.

Per the issue ratification (`[gate:ratify]` comment, A1=A / A2=A / A3=A): land the kwarg with conservative 7-day default, post-rerank application point, and ship as-is — sweep harness deferred to a follow-up.

## Tests

`tests/test_retrieve_v2_temporal_sort.py` (23 cases):

- `_belief_age_seconds` boundaries: zero, future timestamp, malformed, empty, naive UTC.
- `_apply_temporal_decay` invariants: empty input, zero/negative half-life, locked pinning, locked-internal order preserved, equal-age stability.
- Decay-math boundaries at `age = half_life` (factor 0.5) and `age = 2 * half_life` (factor 0.25).
- Resolver precedence: env > kwarg > TOML > default; non-positive / non-numeric env falls through; non-positive kwarg falls through.
- `retrieve_v2` integration: off-byte-identical, locked head pin, explicit half-life kwarg flow.

Full pytest suite: 2746 passed, 41 skipped — no regressions on existing retrieval tests.

## Borderline design call

`retrieve_v2` does not surface per-belief scores out of `retrieve_with_tiers`, so the wrapper has only the merged order to work from. I'm using `1 / (rank + 1)` as a proxy "score" that the decay multiplies against. This matches the issue's closing-comment lean toward "multiplies the final score," but flagging it explicitly because:

- A reviewer might prefer threading score back through `retrieve_with_tiers` so the decay multiplies a real composite. That's a larger contract change (touches `retrieve()` + `retrieve_with_tiers` return tuple).
- Alternative: drop the rank-proxy and use a constant 1.0, so decay alone re-orders the tail. Simpler math, but then a fresh L1 hit can outrank a fresh L2.5 entity hit on age delta alone, which feels wrong relative to the upstream pipeline's lane-priority intent.

Currently shipping with the rank-proxy. Push back here if a different shape is wanted.

## Out of scope

- `tests/temporal_blend_sweep.py` bench-evidence harness (A3=A — follow-up issue).
- Adaptive-meta-belief exploration (#480 — separate thread).
- `[retrieval] temporal_half_life_seconds` documentation in `.aelfrice.toml.example` if one exists (didn't find one in tree; can add if pointed at the right file).

## Refs

- Issue: #473
- Calibration blocker: #437
- Adapter call site: `benchmarks/structmemeval_adapter.py:264-272`
- Public surface: `src/aelfrice/retrieval.py::retrieve_v2`

## Summary by Sourcery

Add optional temporal recency re-ranking to retrieve_v2 while keeping default retrieval order unchanged for existing callers.

New Features:
- Introduce temporal_sort and temporal_half_life_seconds options to retrieve_v2 to enable half-life based recency decay on merged retrieval results.
- Expose configuration of temporal half-life via environment variable, TOML config, or explicit kwarg with a 7-day default.

Enhancements:
- Implement temporal half-life resolution helper and recency-based decay scoring that respects locked beliefs and preserves upstream ordering stability.

Tests:
- Add comprehensive tests covering belief age calculation, temporal decay behavior, configuration precedence, and retrieve_v2 integration with temporal_sort enabled and disabled.

## Release Notes

* **New Features**
  * Added temporal decay-based re-ranking to retrieval results, prioritizing more recent content while maintaining locked items at the top.

* **Documentation**
  * Updated documentation describing temporal sorting behavior with locked item preservation.

* **Tests**
  * Added comprehensive test suite validating temporal re-ranking functionality and edge cases.

### CODE REVIEW

**Comment by yoshi280** [comment]
[claim:review:Toug:2026-05-08T07:56:09Z]

**Comment by yoshi280** [comment]
[release:review:Toug:2026-05-08T07:57:31Z]

**Comment by yoshi280** [comment]
[claim:review:setr:2026-05-08T07:57:48Z]

**Comment by yoshi280** [comment]
[release:review:setr:2026-05-08T07:58:50Z]
