### ISSUE TITLE
StructMemEval adapter calls retrieve_v2() with unsupported temporal_sort kwarg

### ISSUE THREAD

**Issue by yoshi280** [robotrocketscience/aelfrice#473]
Discovered while running the calibration pass for #437 with `/tmp/StructMemEval` populated. The adapter never reached this point in the prior canonical run because the data dir was missing — the "No cases found" silent-return path masked the real bug.

## Symptom

```
$ uv run python benchmarks/structmemeval_adapter.py --task location --bench big --retrieve-only /tmp/sme_smoke.json
Loading StructMemEval cases: task=location, bench=big
Loaded 42 cases

--- static_001: 3 sessions, 30 messages, 1 queries ---
Traceback (most recent call last):
  File ".../benchmarks/structmemeval_adapter.py", line 587, in <module>
    main()
  File ".../benchmarks/structmemeval_adapter.py", line 518, in main
    case_result: CaseResult = run_case(...)
  File ".../benchmarks/structmemeval_adapter.py", line 401, in run_case
    retrieved: str = query_aelfrice(store, query.question, budget=budget)
  File ".../benchmarks/structmemeval_adapter.py", line 264, in query_aelfrice
    result = retrieve(...)
TypeError: retrieve_v2() got an unexpected keyword argument 'temporal_sort'
```

## Diagnosis

`benchmarks/structmemeval_adapter.py:264-272` calls:
```python
result = retrieve(
    store=store,
    query=question,
    budget=budget,
    include_locked=False,
    use_hrr=True,
    use_bfs=True,
    temporal_sort=True,
)
```

The `retrieve` symbol resolves to `retrieve_v2` in `src/aelfrice/retrieval.py:1246`. That function's parameter list ends at `bm25f_cache` — there is no `temporal_sort` kwarg.

`git log -S "temporal_sort" -- benchmarks/structmemeval_adapter.py src/aelfrice/retrieval.py` shows the kwarg was introduced in #54 (P1 benchmark foundation) and never reconciled with `retrieve_v2`'s signature.

## Impact on #437

The canonical pass at `benchmarks/results/v2.0.0.json` shows all 4 StructMemEval invocations (location / accounting / recommendations / tree) failing with `"adapter exited 0 but did not write $TMPDIR/T/structmemeval_<task>.json"`. With data dirs populated, those failures will switch from silent-no-output (exit 0) to loud `TypeError` (exit 1). Either way the canonical numbers stay placeholder until this is fixed.

## Fix directions

1. **Add `temporal_sort` to `retrieve_v2`** — the wrapper's stated purpose is to mirror the lab v2.0.0 retrieval signature. If the lab supports temporal sorting, this is the right fix and the public surface gains a useful knob. Cost: a real design call on what `temporal_sort` means (recency-weighted re-rank? `created_at DESC`? interaction with BM25F / posterior_weight?).
2. **Drop `temporal_sort=True` from the adapter** — accept the public surface's default ordering, document the deviation. The adapter docstring at line 262 says temporal sort "helps the reader identify the current state vs historical states" for structured queries — losing it may cost score on location/accounting/recommendations/tree. Cost: bench-measurable score delta.

## Related dispatcher contract gap

The dispatcher currently conflates three different exit states under one error message:
- data dir missing (skipped, not a real failure)
- adapter crashed mid-run (real failure)
- adapter ran but produced no cases (silent — what happened on the prior canonical run)

The #437 gate commit (60e1b68) called for an `exit_code 2 = skipped_data_missing` contract. This incident is evidence the contract should be three-state: `0 = ok`, `2 = skipped_data_missing`, `1 = adapter_error`, with the dispatcher classifying accordingly. Worth a separate issue for the dispatcher work — flagging here for cross-link.

## Refs

- Adapter call: `benchmarks/structmemeval_adapter.py:264-272`
- Public surface: `src/aelfrice/retrieval.py:1246-1262`
- Calibration blocker: #437
- Origin commit: #54 (P1 benchmark foundation)

**Comment by yoshi280** [comment]
[claim:issue:Setr:2026-05-08T07:09:33Z]

**Comment by yoshi280** [comment]
**Design direction picked: option (1) — add `temporal_sort` to `retrieve_v2()` as a recency-weighted blend, not a hard re-sort.**

Semantics agreed:
- New kwarg `temporal_sort: bool = False` on `retrieve_v2()`. Default False = zero behavior change for the 7 working canonical adapters (MAB×4, LoCoMo, LongMemEval, AMA-Bench), so their tolerance bands from runs 1–3 of the calibration stay valid.
- When True: blend recency into the score via multiplicative half-life decay rather than hard `created_at DESC` sort. Preserves score-ordering invariants for downstream consumers while still surfacing "current state vs historical states" for structured queries.
- StructMemEval adapter passes `temporal_sort=True`; no other public caller flips it on at this stage.

## Open design asks (require ratification before implementation)

1. **Half-life parameter** — needs a name, default value, and a bench-evidence path. Candidates:
   - `temporal_half_life_seconds: float | None = None` with default derived from the corpus's `created_at` spread
   - Hard-coded conservative default (e.g. 7 days = 604800s) tunable via `.aelfrice.toml`
   - Per-call override only, no global default
2. **Where in the pipeline does the blend apply?**
   - Pre-rerank: blend recency into BM25F score before posterior re-rank. Feeds into composition tracker work (#154).
   - Post-rerank: blend recency into the final score after BM25F + posterior + edge-type rerank. Cleaner separation, but loses interaction with posterior signals.
3. **Interaction with `posterior_weight` and `use_bm25f`** — does temporal_sort multiply with the posterior factor or replace part of it? The composition tracker spec (#154) is the right home for this once that's relabeled v2.1.
4. **Bench evidence to set the half-life** — needs a sweep harness similar to the BM25F retrieve_uplift fixture (`tests/retrieve_uplift_runner.py`). Suggest landing a `tests/temporal_blend_sweep.py` that varies half-life across {1h, 1d, 7d, 30d, ∞} and reports NDCG@k delta on StructMemEval's structured queries.

## Calibration-blocker status

Currently 7/11 canonical invocations succeed; StructMemEval ×4 will stay blocked on this issue. Calibration runs 2 + 3 are paused until this fix lands so we don't burn ~70min of wall-time on partial bands that get re-derived after the fix.

## Refs

- v2.1 milestone tracker: filed today, this issue is in scope
- Calibration session 2026-05-08: 7/11 ok, 4/11 blocked here
- `retrieve_v2` signature: `src/aelfrice/retrieval.py:1246-1262`
- Adapter call site: `benchmarks/structmemeval_adapter.py:264-272`

**Comment by yoshi280** [comment]
[release:issue:Setr:2026-05-08T07:12:50Z]

**Comment by yoshi280** [comment]
[gate:ratify]

This block supersedes the prose design-direction comment above. Three asks open. Reply `ratify: A1=A, A2=B, A3=A` (or any subset) or use thumbs-up reactions on this comment to ratify the recommendations.

---

**Ask 1: Half-life parameter shape for `temporal_sort` recency-weighted blend?**

  A. **`temporal_half_life_seconds: float = 604800`** (7-day default, override in `[retrieval]` section of `.aelfrice.toml`).
     Trade: defaults work for most corpora; edge cases need config; one knob to document. **(Recommended)**
  B. Per-call only on `retrieve_v2()` signature, no global default, no `.toml` knob.
     Trade: every caller must specify; matches "explicit > implicit" but spreads policy across callers.
  C. Auto-derive from corpus `created_at` spread (e.g. half-life = median(created_at - max(created_at)) / k).
     Trade: more correct in theory; depends on corpus having stable temporal distribution; brittle on small/cold stores.

  Defer: explain why and target version.

---

**Ask 2: Where in the pipeline does the recency blend apply?**

  A. **Post-rerank** — apply blend as a final multiplicative factor after BM25F + posterior + edge-type rerank.
     Trade: cleanest separation; loses any interaction with posterior signals; works regardless of which other lanes are active. **(Recommended)**
  B. Pre-rerank — blend recency into the BM25F score before posterior re-rank.
     Trade: feeds into composition tracker (#154); tighter coupling; lets posterior signals see the recency-weighted candidates.
  C. Inside the posterior factor itself — make `posterior_weight` recency-aware.
     Trade: most principled if you accept "recency is a posterior prior" framing; biggest blast radius — affects every retrieval consumer of `posterior_weight`, not just `temporal_sort` callers.

  Defer: explain why and target version.

---

**Ask 3: Bench evidence to set the half-life default?**

  A. **Land the kwarg with conservative default (7d), file follow-up issue for sweep harness, ship as-is.**
     Trade: unblocks #437 calibration immediately; ships an unsupported default; sweep happens in a later PR. **(Recommended)**
  B. Land the kwarg AND a `tests/temporal_blend_sweep.py` harness in the same PR (sweep across {1h, 1d, 7d, 30d, ∞}, report NDCG@k delta on StructMemEval structured queries).
     Trade: ships with bench evidence; delays #437 calibration unblock by however long the sweep harness takes (~few days).
  C. Block the kwarg until the sweep harness lands separately and produces a recommended default.
     Trade: most rigorous; #437 calibration stays partial until the sweep completes (estimated ≥1 week).

  Defer: explain why and target version.

---

Sessions: read this comment as the canonical asks surface. The prior prose design-direction comment is informational only.

**Comment by yoshi280** [comment]
I'm ok with all recommended. I am curious about the half life though, can we test what it would look like if that value itself were constantly updated as a meta belief, maybe we introduce a new concept of meta belief that is driven by the same Bayesian engine but lives separately from the rest of the brain graph

**Comment by yoshi280** [comment]
## Ratification recorded — 2026-05-08

Per the operator's reply above ("I'm ok with all recommended"):

| Ask | Choice | Implication |
|---|---|---|
| A1 — Half-life parameter shape | **A** | `temporal_half_life_seconds: float = 604800` (7-day default, override in `[retrieval]` of `.aelfrice.toml`) |
| A2 — Pipeline application point | **A** | Post-rerank: multiplicative factor after BM25F + posterior + edge-type rerank |
| A3 — Bench evidence path | **A** | Land kwarg with conservative default; file follow-up sweep harness; ship as-is |

`[gate:ratify]` is closed for this issue. No further ratification needed before implementation.

## Forward-looking curiosity captured

The operator's curiosity about adaptive half-life (treating it as a meta-belief governed by the same Bayesian engine but in a separate namespace from the brain graph) is **out of scope for v2.1** but captured for v2.x exploration in a dedicated issue. This stays as a static 7-day default for now; the adaptive variant has its own thread.

## Implementation scope (for the next session that picks this up)

1. Add `temporal_sort: bool = False` and `temporal_half_life_seconds: float = 604800` kwargs to `retrieve_v2()` in `src/aelfrice/retrieval.py:1246`.
2. Implement multiplicative decay: `weight *= 2 ** (-age_seconds / half_life_seconds)` where `age_seconds = now - belief.created_at`. Apply as a final factor in the score composition, after BM25F + posterior + edge-type rerank — i.e. it sees the post-rerank order and re-weights from there.
3. Wire `[retrieval] temporal_half_life_seconds` config knob in `.aelfrice.toml` reader.
4. Update `benchmarks/structmemeval_adapter.py:264-272` to pass `temporal_sort=True`. Verify it now reaches the `run_case` body without `TypeError`.
5. Tests: unit on the decay function (boundary cases at 0, half_life, 2×half_life), integration on `retrieve_v2()` with `temporal_sort=True/False` showing recent beliefs rank higher when on, identical ordering when off.
6. Follow-up issue (separate PR): `tests/temporal_blend_sweep.py` harness across half-life {1h, 1d, 7d, 30d, ∞} with NDCG@k delta on StructMemEval — bench evidence to validate the 7-day default isn't pathological. **Out of scope for the kwarg-landing PR.**
7. After the kwarg PR lands: re-run the #437 calibration ×3 against full 11/11 to populate StructMemEval ×4 in the canonical numbers and set tolerance bands.

Borderline rook-tier: mostly mechanical, but the post-rerank composition order needs a small design decision on whether the decay multiplies the final score or rebalances within the candidate set. Lean toward "multiplies the final score" — it's the simpler-to-reason-about contract — but flag as a borderline design ask in the PR description.

**Comment by yoshi280** [comment]
[claim:issue:Kulili:2026-05-08T07:43:29Z]

**Comment by yoshi280** [comment]
[release:issue:Kulili:2026-05-08T07:51:55Z]

**Comment by robotrocketscience** [comment]
Bench-evidence follow-up for the 7-day half-life default (A3=A loose end) filed as #487.
